### ISSUE TITLE
Help kids pause to feel their heartbeat

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/preK-emotions-app#67]
Kids rarely feel their heart (Observed Pilot 1, Weeks 1-7). They just pick one of the heartbeat images. In the wireframes we had an image to help guide them but I guess we lost it when we flipped to the horizontal layout. 

What if we showed a hand on heart image first, without the heartbeats? And then the heartbeats appeared after a moment?

For reference, the wireframe:
![wireframehandonheart](https://user-images.githubusercontent.com/24419423/53831627-3ffea800-3f53-11e9-91cc-fce986325834.PNG)

and the current design:
![screenshot_2019-03-05-14-25-30](https://user-images.githubusercontent.com/24419423/53831639-45f48900-3f53-11e9-83d3-08cb078dc0b7.png)

**Comment by lczito** [comment]
I like that

**Comment by ehamner** [comment]
From Rachelle: 
I like the image of a person feeling their heart....better yet, if that person was an actual child placing their hand on their chest....The children may not have equated the symbol of a heart with their actual heart.....

**Comment by ehamner** [comment]
@mo11yj thoughts on what would be a more consistent design - an icon, photo, short video? The kids found the yoga videos useful to know what to do. I could do a photo or video with Katie if we want to go that route.

**Comment by mo11yj** [comment]
I think an illustration would be most consistent with the design; however, a video might be most clear to help students actually complete the action of putting their hands on their hearts.

So I think it is best to go in the video direction. I can mock up the screens for it over the weekend, but if you want to get started implementing, I imagine it would be one screen with the instruction and video, and then have it auto advance to the screen with "how fast is your heart beating?" after a few seconds or two loops of the video. (Since their hand should be on their heart, it might be hard to press a button, especially if they are holding the kindle in the other hand)

**Comment by mo11yj** [comment]
Screens: zpl.io/VOP586r , zpl.io/bJvnjWn

<img width="1045" alt="Screen Shot 2019-03-09 at 11 23 52 AM" src="https://user-images.githubusercontent.com/25698542/54074222-e1407380-425d-11e9-9b18-ea3c9b873089.png">

<img width="1043" alt="Screen Shot 2019-03-09 at 11 23 58 AM" src="https://user-images.githubusercontent.com/25698542/54074223-e6052780-425d-11e9-8f4b-88139eeddec1.png">

**Comment by rachelleduffy** [comment]
Hello...I am unable to view the video....What does this do?

**Comment by mo11yj** [comment]
This is just a screenshot, if you decide to go the video route, I think Emily said she would record something to fit here.

**Comment by ehamner** [comment]
I added a short video clip to the res-raw folder in box. I wish she had held her hand there a little longer. If it isn't long enough for the audio clip I guess we can just stay on the last frame.

[HandonHeart.zip](https://github.com/CMU-CREATE-Lab/preK-emotions-app/files/2966901/HandonHeart.zip)

**Comment by tasota** [comment]
@kaylaleung take a look at the RecordUseWordsActivity for using fragments to display in 1 activity.
